### ISSUE TITLE
App1 Variable Convention Issue

### ISSUE THREAD

**Issue by H-a-M-m-Ad** [H-a-M-m-Ad/17_Feb_Sesssion#1]
1. sadasda
2. das
3. dsa
4. d
5. as
6. da
7. sd
8. asd
9. a
10. sd
11. as
12. da
13. sd
14. as
15. dsad

**Comment by Hasssaanali** [comment]
resolved

**Comment by H-a-M-m-Ad** [comment]
thanks for it

**Comment by Hassamkazmi** [comment]
Nice

**Comment by H-a-M-m-Ad** [comment]
@Hasssaanali  you said but it is not working you liar

**Comment by Hasssaanali** [comment]
okay
